#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wormhole"
name = "Magic-Wormhole"
description.en = "Transit Relay server for Magic-Wormhole"
description.fr = "Transit Relay server for Magic-Wormhole"

version = "0.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://example.com"
demo = "https://demo.example.com"
code = "https://github.com/magic-wormhole/magic-wormhole-transit-relay"


[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/magic-wormhole/magic-wormhole-transit-relay/archive/refs/tags/0.4.0.tar.gz"
    sha256 = "93ddeac8bd4e0c8d68216bd7007468ed669b6a14018306987e30670b1da0a291"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3-dev, python3-venv, python3-pip, python3-setuptools, python3-twisted"
